version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: panneaux
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data:
